// util/brincadeiras.js

const brincadeiras = [
  { id: 1, tipo: "Quem Sou Eu", pergunta: `🎭 *QUEM SOU EU?*\n\n🤔 Dica 1: Sou brasileiro.\n🤔 Dica 2: Fiquei muito conhecido por driblar bem.\n🤔 Dica 3: Já joguei no Barcelona.\n\n❓Quem sou eu?` },
  { id: 2, tipo: "Desafio Rapidez", pergunta: `🏃‍♂️ *DESAFIO DE RAPIDEZ!*\n\n✏️ Quem mandar a *caneta* primeiro no grupo, ganha!` },
  { id: 3, tipo: "Emoji Challenge", pergunta: `🐱 *EMOJI CHALLENGE!*\n\nQuem mandar o emoji *🐱* primeiro no grupo, ganha!` },
  { id: 4, tipo: "Complete o Versículo", pergunta: `📖 *COMPLETE O VERSÍCULO:*\n\n\"Porque Deus amou o mundo de tal maneira que...\"\n\nA) Deu sua vida por nós.\nB) Entregou os Dez Mandamentos.\nC) Deu o seu Filho unigênito.\nD) Criou o Jardim do Éden.\n\nEscolha a alternativa correta (A, B, C ou D).` },
  { id: 5, tipo: "Verdade ou Mentira", pergunta: `⚡ *VERDADE OU MENTIRA?*\n\n\"A formiga é mais forte que o elefante.\"\n\n✅ Verdade  ❌ Mentira\n\nResponda com seu palpite!` },
  { id: 6, tipo: "Adivinha o Filme", pergunta: `🎬 *ADIVINHA O FILME:*\n\n🍿 Dica 1: Tem uma princesa.\n🕰️ Dica 2: Um baile inesquecível.\n🥿 Dica 3: Um sapatinho perdido...\n\n🎥 Que filme é esse?` },
  { id: 7, tipo: "Desembaralha a Palavra", pergunta: `🔤 *DESAFIO: DESEMBARALHA A PALAVRA!*\n\nPalavra: *SEJSU*\nDica: É alguém muito importante para os cristãos.` },
  { id: 8, tipo: "Quem Sou Eu", pergunta: `🎭 *QUEM SOU EU?*\n\n🤔 Dica 1: Fui o primeiro homem.\n🤔 Dica 2: Vivi no Jardim do Éden.\n🤔 Dica 3: Meu filho mais conhecido foi Caim.\n\n❓Quem sou eu?` },
  { id: 9, tipo: "Desafio Rapidez", pergunta: `🏃‍♀️ *DESAFIO DE RAPIDEZ!*\n\n🔥 Quem mandar o emoji *🔥* primeiro no grupo, ganha!` },
  { id: 10, tipo: "Pergunta Rápida", pergunta: `❓ *PERGUNTA RÁPIDA:*\n\nQual é o livro mais famoso da Bíblia?\n\nA) Êxodo\nB) Salmos\nC) Gênesis\nD) Mateus\n\nResponda com a letra correta!` },

  { id: 11, tipo: "Quem Sou Eu", pergunta: `🎭 *QUEM SOU EU?*\n\n🤔 Dica 1: Sou uma mulher forte na Bíblia.\n🤔 Dica 2: Venci o gigante Golias.\n\n❓Quem sou eu?` },
  { id: 12, tipo: "Desafio Rapidez", pergunta: `🏃‍♂️ *DESAFIO DE RAPIDEZ!*\n\n🍎 Quem mandar a palavra *maçã* primeiro no grupo, ganha!` },
  { id: 13, tipo: "Emoji Challenge", pergunta: `🐶 *EMOJI CHALLENGE!*\n\nQuem mandar o emoji *🐶* primeiro no grupo, ganha!` },
  { id: 14, tipo: "Complete o Versículo", pergunta: `📖 *COMPLETE O VERSÍCULO:*\n\n\"O Senhor é meu pastor; nada me faltará...\"\n\nA) Ele me guia.\nB) Ele me dá força.\nC) Ele me protege.\nD) Ele é minha luz.\n\nEscolha a alternativa correta (A, B, C ou D).` },
  { id: 15, tipo: "Verdade ou Mentira", pergunta: `⚡ *VERDADE OU MENTIRA?*\n\n\"O dilúvio durou 40 dias e 40 noites.\"\n\n✅ Verdade  ❌ Mentira\n\nResponda com seu palpite!` },
  { id: 16, tipo: "Adivinha o Filme", pergunta: `🎬 *ADIVINHA O FILME:*\n\n🐒 Dica 1: Um macaco falante.\n🕵️ Dica 2: Um detetive.\n\n🎥 Que filme é esse?` },
  { id: 17, tipo: "Desembaralha a Palavra", pergunta: `🔤 *DESAFIO: DESEMBARALHA A PALAVRA!*\n\nPalavra: *LOTMPE*\nDica: Um lugar sagrado para os cristãos.` },
  { id: 18, tipo: "Quem Sou Eu", pergunta: `🎭 *QUEM SOU EU?*\n\n🤔 Dica 1: Sou o filho de Abraão.\n🤔 Dica 2: Tenho dois filhos famosos.\n\n❓Quem sou eu?` },
  { id: 19, tipo: "Desafio Rapidez", pergunta: `🏃‍♀️ *DESAFIO DE RAPIDEZ!*\n\n⚡ Quem mandar o emoji *⚡* primeiro no grupo, ganha!` },
  { id: 20, tipo: "Pergunta Rápida", pergunta: `❓ *PERGUNTA RÁPIDA:*\n\nQuantos livros tem o Novo Testamento?\n\nA) 27\nB) 39\nC) 66\nD) 12\n\nResponda com a letra correta!` },

  { id: 21, tipo: "Quem Sou Eu", pergunta: `🎭 *QUEM SOU EU?*\n\n🤔 Dica 1: Fui o libertador dos israelitas.\n🤔 Dica 2: Dividi o Mar Vermelho.\n\n❓Quem sou eu?` },
  { id: 22, tipo: "Desafio Rapidez", pergunta: `🏃‍♂️ *DESAFIO DE RAPIDEZ!*\n\n💧 Quem mandar o emoji *💧* primeiro no grupo, ganha!` },
  { id: 23, tipo: "Emoji Challenge", pergunta: `🐵 *EMOJI CHALLENGE!*\n\nQuem mandar o emoji *🐵* primeiro no grupo, ganha!` },
  { id: 24, tipo: "Complete o Versículo", pergunta: `📖 *COMPLETE O VERSÍCULO:*\n\n\"No princípio, Deus criou...\"\n\nA) o céu e a terra.\nB) o homem.\nC) os animais.\nD) a luz.\n\nEscolha a alternativa correta (A, B, C ou D).` },
  { id: 25, tipo: "Verdade ou Mentira", pergunta: `⚡ *VERDADE OU MENTIRA?*\n\n\"Jesus transformou água em vinho.\"\n\n✅ Verdade  ❌ Mentira\n\nResponda com seu palpite!` },
  { id: 26, tipo: "Adivinha o Filme", pergunta: `🎬 *ADIVINHA O FILME:*\n\n🦁 Dica 1: Rei da selva.\n👑 Dica 2: É uma animação famosa.\n\n🎥 Que filme é esse?` },
  { id: 27, tipo: "Desembaralha a Palavra", pergunta: `🔤 *DESAFIO: DESEMBARALHA A PALAVRA!*\n\nPalavra: *SAMAEL*\nDica: Nome de um anjo.` },
  { id: 28, tipo: "Quem Sou Eu", pergunta: `🎭 *QUEM SOU EU?*\n\n🤔 Dica 1: Sou conhecido como o apóstolo que negou Jesus três vezes.\n\n❓Quem sou eu?` },
  { id: 29, tipo: "Desafio Rapidez", pergunta: `🏃‍♀️ *DESAFIO DE RAPIDEZ!*\n\n🌟 Quem mandar o emoji *🌟* primeiro no grupo, ganha!` },
  { id: 30, tipo: "Pergunta Rápida", pergunta: `❓ *PERGUNTA RÁPIDA:*\n\nQuem construiu a arca para sobreviver ao dilúvio?\n\nA) Moisés\nB) Noé\nC) Abraão\nD) Davi\n\nResponda com a letra correta!` },

  { id: 31, tipo: "Quem Sou Eu", pergunta: `🎭 *QUEM SOU EU?*\n\n🤔 Dica 1: Sou o irmão de Moisés.\n🤔 Dica 2: Fui um profeta importante.\n\n❓Quem sou eu?` },
  { id: 32, tipo: "Desafio Rapidez", pergunta: `🏃‍♂️ *DESAFIO DE RAPIDEZ!*\n\n🍇 Quem mandar a palavra *uva* primeiro no grupo, ganha!` },
  { id: 33, tipo: "Emoji Challenge", pergunta: `🐰 *EMOJI CHALLENGE!*\n\nQuem mandar o emoji *🐰* primeiro no grupo, ganha!` },
  { id: 34, tipo: "Complete o Versículo", pergunta: `📖 *COMPLETE O VERSÍCULO:*\n\n\"Eu sou o caminho, a verdade e...\"\n\nA) a luz.\nB) a vida.\nC) a paz.\nD) a salvação.\n\nEscolha a alternativa correta (A, B, C ou D).` },
  { id: 35, tipo: "Verdade ou Mentira", pergunta: `⚡ *VERDADE OU MENTIRA?*\n\n\"Jesus nasceu em Nazaré.\"\n\n✅ Verdade  ❌ Mentira\n\nResponda com seu palpite!` },
  { id: 36, tipo: "Adivinha o Filme", pergunta: `🎬 *ADIVINHA O FILME:*\n\n❄️ Dica 1: Princesa do gelo.\n🎤 Dica 2: Tem uma música famosa \"Let it go\".\n\n🎥 Que filme é esse?` },
  { id: 37, tipo: "Desembaralha a Palavra", pergunta: `🔤 *DESAFIO: DESEMBARALHA A PALAVRA!*\n\nPalavra: *MEISOS*\nDica: Nome do líder que tirou os israelitas do Egito.` },
  { id: 38, tipo: "Quem Sou Eu", pergunta: `🎭 *QUEM SOU EU?*\n\n🤔 Dica 1: Sou o discípulo amado.\n\n❓Quem sou eu?` },
  { id: 39, tipo: "Desafio Rapidez", pergunta: `🏃‍♀️ *DESAFIO DE RAPIDEZ!*\n\n🌈 Quem mandar o emoji *🌈* primeiro no grupo, ganha!` },
  { id: 40, tipo: "Pergunta Rápida", pergunta: `❓ *PERGUNTA RÁPIDA:*\n\nQual é o primeiro livro da Bíblia?\n\nA) Gênesis\nB) Êxodo\nC) Levítico\nD) Números\n\nResponda com a letra correta!` },

  { id: 41, tipo: "Quem Sou Eu", pergunta: `🎭 *QUEM SOU EU?*\n\n🤔 Dica 1: Sou o profeta que enfrentou os profetas de Baal.\n\n❓Quem sou eu?` },
  { id: 42, tipo: "Desafio Rapidez", pergunta: `🏃‍♂️ *DESAFIO DE RAPIDEZ!*\n\n🍉 Quem mandar a palavra *melancia* primeiro no grupo, ganha!` },
  { id: 43, tipo: "Emoji Challenge", pergunta: `🐼 *EMOJI CHALLENGE!*\n\nQuem mandar o emoji *🐼* primeiro no grupo, ganha!` },
  { id: 44, tipo: "Complete o Versículo", pergunta: `📖 *COMPLETE O VERSÍCULO:*\n\n\"O Senhor é a minha luz e...\"\n\nA) a minha salvação.\nB) a minha força.\nC) o meu pastor.\nD) o meu refúgio.\n\nEscolha a alternativa correta (A, B, C ou D).` },
  { id: 45, tipo: "Verdade ou Mentira", pergunta: `⚡ *VERDADE OU MENTIRA?*\n\n\"Paulo escreveu a maioria das cartas do Novo Testamento.\"\n\n✅ Verdade  ❌ Mentira\n\nResponda com seu palpite!` },
  { id: 46, tipo: "Adivinha o Filme", pergunta: `🎬 *ADIVINHA O FILME:*\n\n🧙‍♂️ Dica 1: Um menino que vai para uma escola de magia.\n⚡ Dica 2: Tem uma cicatriz na testa.\n\n🎥 Que filme é esse?` },
  { id: 47, tipo: "Desembaralha a Palavra", pergunta: `🔤 *DESAFIO: DESEMBARALHA A PALAVRA!*\n\nPalavra: *BLEME*\nDica: Cidade onde Jesus nasceu.` },
  { id: 48, tipo: "Quem Sou Eu", pergunta: `🎭 *QUEM SOU EU?*\n\n🤔 Dica 1: Fui traído por um beijo.\n\n❓Quem sou eu?` },
  { id: 49, tipo: "Desafio Rapidez", pergunta: `🏃‍♀️ *DESAFIO DE RAPIDEZ!*\n\n🍀 Quem mandar o emoji *🍀* primeiro no grupo, ganha!` },
  { id: 50, tipo: "Pergunta Rápida", pergunta: `❓ *PERGUNTA RÁPIDA:*\n\nQuem foi o rei que construiu o templo em Jerusalém?\n\nA) Davi\nB) Salomão\nC) Saul\nD) Josias\n\nResponda com a letra correta!` },
   { id: 51, tipo: "Desafio Ação", pergunta: `🏃‍♂️ *DESAFIO DE AÇÃO!*\n\nQuem mandar primeiro no grupo uma foto de um *perfume*, ganha!` },
  { id: 52, tipo: "Desafio Ação", pergunta: `🏃‍♀️ *DESAFIO DE AÇÃO!*\n\nQuem tirar a primeira foto de um objeto *verde* e mandar aqui, ganha!` },
  { id: 53, tipo: "Desafio Ação", pergunta: `⚡ *DESAFIO DE AÇÃO!*\n\nQuem mandar primeiro no grupo a palavra *caneta* ganha!` },
  { id: 54, tipo: "Desafio Ação", pergunta: `🔥 *DESAFIO DE AÇÃO!*\n\nQuem mandar o emoji *🔥* primeiro no grupo, ganha!` },
  { id: 55, tipo: "Desafio Ação", pergunta: `🌸 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *flor* primeiro no grupo, ganha!` },
  { id: 56, tipo: "Desafio Ação", pergunta: `📚 *DESAFIO DE AÇÃO!*\n\nQuem mandar primeiro uma foto de um *livro* ganha!` },
  { id: 57, tipo: "Desafio Ação", pergunta: `🎵 *DESAFIO DE AÇÃO!*\n\nQuem mandar primeiro a palavra *música* ganha!` },
  { id: 58, tipo: "Desafio Ação", pergunta: `🐶 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *cachorro* primeiro no grupo, ganha!` },
  { id: 59, tipo: "Desafio Ação", pergunta: `☕ *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *xícara de café* primeiro no grupo, ganha!` },
  { id: 60, tipo: "Desafio Ação", pergunta: `🚗 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *carro* primeiro no grupo, ganha!` },

  { id: 61, tipo: "Desafio Ação", pergunta: `👟 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *par de tênis* primeiro no grupo, ganha!` },
  { id: 62, tipo: "Desafio Ação", pergunta: `🖊️ *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *caneta azul* primeiro no grupo, ganha!` },
  { id: 63, tipo: "Desafio Ação", pergunta: `🪞 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *espelho* primeiro no grupo, ganha!` },
  { id: 64, tipo: "Desafio Ação", pergunta: `📱 *DESAFIO DE AÇÃO!*\n\nQuem mandar um *print da tela inicial do celular* primeiro, ganha!` },
  { id: 65, tipo: "Desafio Ação", pergunta: `🕶️ *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *óculos* primeiro no grupo, ganha!` },
  { id: 66, tipo: "Desafio Ação", pergunta: `🖼️ *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *quadro na parede* primeiro no grupo, ganha!` },
  { id: 67, tipo: "Desafio Ação", pergunta: `🧢 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *boné* primeiro no grupo, ganha!` },
  { id: 68, tipo: "Desafio Ação", pergunta: `🖥️ *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *computador ligado* primeiro, ganha!` },
  { id: 69, tipo: "Desafio Ação", pergunta: `💡 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *lâmpada acesa* primeiro no grupo, ganha!` },
  { id: 70, tipo: "Desafio Ação", pergunta: `🍎 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *fruta vermelha* primeiro no grupo, ganha!` },
  { id: 71, tipo: "Desafio Ação", pergunta: `📷 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma *selfie fazendo careta* primeiro no grupo, ganha!` },
  { id: 72, tipo: "Desafio Ação", pergunta: `👕 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *camiseta branca* primeiro no grupo, ganha!` },
  { id: 73, tipo: "Desafio Ação", pergunta: `📺 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *TV ligada* primeiro no grupo, ganha!` },
  { id: 74, tipo: "Desafio Ação", pergunta: `🎧 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *fone de ouvido* primeiro no grupo, ganha!` },
  { id: 75, tipo: "Desafio Ação", pergunta: `🪑 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *cadeira* primeiro no grupo, ganha!` },
  { id: 76, tipo: "Desafio Ação", pergunta: `📦 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *caixa* primeiro no grupo, ganha!` },
  { id: 77, tipo: "Desafio Ação", pergunta: `🧃 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *suco* primeiro no grupo, ganha!` },
  { id: 78, tipo: "Desafio Ação", pergunta: `⌚ *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de um *relógio de pulso* primeiro no grupo, ganha!` },
  { id: 79, tipo: "Desafio Ação", pergunta: `🥤 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *garrafa ou copo de água* primeiro no grupo, ganha!` },
  { id: 80, tipo: "Desafio Ação", pergunta: `🎒 *DESAFIO DE AÇÃO!*\n\nQuem mandar uma foto de uma *mochila* primeiro no grupo, ganha!` }
];

const respostas = {
  1: "Neymar",
  2: "caneta",
  3: "🐱",
  4: "C",
  5: "Verdade",
  6: "Cinderela",
  7: "JESUS",
  8: "Adão",
  9: "🔥",
  10: "D",

  11: "Davi",
  12: "maçã",
  13: "🐶",
  14: "A",
  15: "Verdade",
  16: "King Kong",
  17: "templo",
  18: "Isaque",
  19: "⚡",
  20: "A",

  21: "Moisés",
  22: "💧",
  23: "🐵",
  24: "A",
  25: "Verdade",
  26: "O Rei Leão",
  27: "Samael",
  28: "Pedro",
  29: "🌟",
  30: "B",

  31: "Arão",
  32: "uva",
  33: "🐰",
  34: "B",
  35: "Mentira",
  36: "Frozen",
  37: "Moisés",
  38: "João",
  39: "🌈",
  40: "A",

  41: "Elias",
  42: "melancia",
  43: "🐼",
  44: "A",
  45: "Verdade",
  46: "Harry Potter",
  47: "Belém",
  48: "Judas",
  49: "🍀",
  50: "B"
};
function gerarBrincadeiraAleatoria() {
  const escolhida = brincadeiras[Math.floor(Math.random() * brincadeiras.length)];
  return escolhida;
}

module.exports = {
  brincadeiras,
  respostas,
  gerarBrincadeiraAleatoria
};