const { mensagemPlataformasParaDicas } = require("./plataformas");

const dicas = [
 "💵 *Com quanto começar?*\nSe você é iniciante, comece com uma banca entre R$ 20 e R$ 50. O objetivo não é enriquecer em um dia, mas entender o funcionamento da plataforma e testar estratégias.",
    "🧠 *Aposte como quem estuda, não como quem joga.*\nUse os primeiros dias para observar padrões, entender o RTP dos jogos e aprender como a plataforma responde às suas apostas.",
  "📉 *Evite girar o slot em sequência sem propósito.*\nCada clique é dinheiro. Se o slot não pagou nada em 30 rodadas, troque de jogo. Persistir no erro é o maior inimigo da sua banca.",
  "🎯 *Escolha slots com RTP acima de 96%.*\nSlots com RTP alto devolvem mais ao longo do tempo. Plataformas como PG Soft e Pragmatic mostram essas taxas.",
  "⏳ *Jogue devagar.*\nDiminua a velocidade dos giros e faça pausas. Isso evita cliques impulsivos e dá tempo para analisar o jogo.",
  "💡 *Melhor horário para jogar?*\nEntre 1h e 6h da manhã há menor volume de jogadores. Isso pode melhorar sua taxa de retorno em plataformas com distribuição por algoritmo de atividade.",
  "🔄 *Use ciclos de teste:*\n10 giros com R$ 0,20\n10 giros com R$ 0,50\nSe não pagar: tchau, jogo\nSe pagar bem: mantenha o ritmo.",
  "🎁 *Nunca aceite bônus sem ler as regras.*\nMuitos bônus impedem você de sacar até cumprir exigências difíceis. Às vezes, o “brinde” vira prisão.",
  "📊 *Registre tudo!*\nTenha uma planilha simples: Jogo | Horário | Aposta | Retorno. Isso vai te mostrar quais jogos valem a pena e quando jogar.",
  "🚫 *Stop loss é lei.*\nDefina um limite de perda (ex: “Se eu perder R$ 30, paro”) e respeite. Jogar na emoção gera prejuízo.",
  "🎰 *Qual slot escolher?*\nPrefira os que têm compra de bônus ou jackpots. Eles pagam menos vezes, mas quando pagam, compensam.",
  "🧪 *Teste antes em modo demo.*\nTodos os jogos têm comportamentos. Use o modo grátis para entender a dinâmica antes de apostar de verdade.",
  "🎯 *Aposte com propósito.*\nNão entre no jogo só por entrar. Espere a porcentagem subir, use plataforma com RTP Live e só entre com sinal claro.",
  "⚠️ *Aumentou a aposta? Aumenta o controle.*\nQuando subir o valor da bet, reduza o número de giros. Proteja sua banca!",
  "📈 *O jogo pagou? Retire e separe.*\nSacou lucro? Separe pelo menos 50% e jogue só com o resto. Garantir o ganho é mais importante que tentar dobrar.",
  "📅 *Crie rotina e metas.*\nEx: Jogar só 1 hora por dia. Meta: R$ 15 de lucro. Fez? Sai. Jogador profissional respeita metas.",
  "🎲 *Varie os jogos, mas mantenha os que rendem.*\nTeste novos slots, mas mantenha os que já provaram dar lucro. Crie uma lista de favoritos rentáveis.",
  "🎯 *Foque em jogabilidade, não em gráfico.*\nAlguns slots são bonitos, mas não pagam bem. Priorize os que têm free spins, multiplicadores e wilds dinâmicos.",
  "💸 *Não existe slot fixo.*\nMesmo que um jogo tenha pagado muito ontem, isso não garante nada hoje. RTP é volátil. Análise constante é essencial.",
  "🧘 *Mentalidade é 80% do sucesso.*\nGanhar é ótimo. Perder faz parte. O segredo é manter a disciplina, não se desesperar, e jogar com cabeça, não com coração.",
  "💡 *Dica Importante:* Sempre analise a tendência antes de apostar!",
   "📉 Nunca dobre o valor da aposta sem estratégia.",
  "💰 Aposte só o que você está disposto a perder.",
  "🕒 Os melhores horários nem sempre são os mais movimentados. Observe!",
  "🎮 Prefira jogos com taxa acima de 90% e jogue com cautela.\n\nOlha links de porcentagem ajuda nas estrategias.\n\n https://slot-pg-soft.prodevreal.com/  ",
  "🔍 Analise o histórico do jogo antes de começar!",
  "📈 *Aproveite os minutos pagantes, mas saiba a hora de parar.*\nO grupo solta de hora em hora alguns minutos com jogos indicados para apostar com maior chance. Para ativar as notificações, use o comando:\n\n`!hora 00:00` (substitua pela hora desejada para receber os alertas).",
  "🙌 *Controle emocional é mais importante que técnica.*\nSe sentir que não está bem emocionalmente, evite jogar. Espere e volte em outro momento com a mente tranquila e foco total.",
  "📌 *Dica*\n\nEvite apostar por impulso. Analise o padrão do jogo, observe os últimos resultados e só entre quando enxergar uma oportunidade clara.\n\n⏳ *Paciência é fundamental!*",
  "💡 *Dica Estratégica*\n\nUse uma planilha para anotar seus jogos, horários, plataformas e resultados. Isso ajuda a identificar padrões, acertos e erros.\n\n📈 Organize, analise e evolua.",
  "🎯 *Dica Importante*\n\nNunca aposte mais do que você pode perder. Isso deve ser uma diversão, não um motivo de estresse.\n\n💬 Reflita sempre: *“Se perder essa banca, minha vida segue bem?”*",
  "🧠 *Controle emocional é chave*\n\nGanhou? Ótimo. Perdeu? Aprenda. Não tente recuperar perdas na emoção, isso é o caminho para prejuízo maior.\n\n🎲 Foque no longo prazo e não em um único dia.",
  "🔎 *Dica Técnica*\n\nPrefira plataformas que mostram o histórico dos últimos jogos. Assim você pode evitar entrar em padrões ruins e aproveitar tendências positivas.\n\n📊 Informação é poder!",
 "📌 *DICA VIP DA PORCENTAGEM* 📌\n🎰 Plataforma em destaque: *PG Soft RTP Live*\n🌐 Acesse: https://slot-pg-soft.prodevreal.com/\n💡 Essa plataforma traz os jogos da PG Soft com porcentagens em tempo real, revelando os mais lucrativos do momento. Ideal para quem quer jogar com estratégia e aumentar suas chances de vitória!\n🎯 *Recomendações de BET:*\n- Bet follow default: JOGUE ATÉ O VALOR DE 2 REAIS\n- Bet minimum: JOGUE NA BET DE 2 REAIS A 10 REAIS\n- Bet maximum: JOGUE ACIMA DE 10 REAIS",
  "🎲 *Dica Avançada*\n\nNunca siga estratégias milagrosas. O sucesso vem com estudo e disciplina, não sorte aleatória.",
  "📉 *Evite perdas grandes*\n\nSe a banca cair 30%, pare e reavalie a estratégia antes de continuar.",
  "🕹️ *Conheça as plataformas*\n\nTeste as plataformas em modo demo antes de apostar dinheiro real.",
  "📅 *Tenha um calendário*\n\nDefina dias e horários para jogar, evitando jogar em horários que costuma perder foco.",
  "🎯 *Meta diária*\n\nEstabeleça uma meta de ganhos e pare quando alcançá-la para evitar perdas por ganância.",
  "📊 *Análise semanal*\n\nRevise suas apostas semanalmente para entender o que funcionou e o que precisa melhorar.",
  "🚫 *Evite jogar cansado*\n\nO cansaço diminui o foco e aumenta a chance de erro. Priorize o descanso.",
  "🔔 *Use alertas*\n\nConfigure notificações para os melhores horários e aproveite as melhores oportunidades.",
  "🧩 *Diversifique*\n\nNão aposte tudo numa só plataforma ou jogo. Diversifique para reduzir riscos.",
  "📈 *Use gráficos*\n\nRegistre seus resultados em gráficos para visualizar seu progresso e padrões.",
  "💬 *Converse e aprenda*\n\nParticipe de grupos de discussão para trocar experiências e aprender com outros jogadores.",
  "⏳ *Timing é tudo*\n\nSaiba quando entrar e quando sair das apostas para maximizar os lucros.",
  "💡 *Dica de ouro*\n\nAposte com a cabeça, não com o coração. Emoção pode ser inimiga da estratégia.",
  "⚠️ *Controle os impulsos*\n\nSe sentir vontade de apostar mais após uma perda, pare. Essa é a hora de respirar e pensar.",
  "🎉 *Celebre as pequenas vitórias*\n\nReconheça seu progresso para manter a motivação sempre alta.",
 "🎯 Dica de consistência, Estabeleça um valor fixo para apostar diariamente e mantenha-se fiel a ele, independente dos resultados do dia.",
  "🔄 Reavalie frequentemente, Revise suas estratégias após cada sessão de apostas para ajustar o que funcionou e eliminar o que não deu certo.",
  "🛑 Sinal de alerta, Se perceber que está apostando para recuperar perdas, pare imediatamente. Isso é sinal de que a emoção está tomando conta.",
  "📚 Estude os jogos, Conheça as regras e particularidades de cada jogo onde aposta para tomar decisões mais informadas.",
  "👥 *Use o grupo com inteligência.*\nBusque dicas e análises confiáveis, mas sempre cheque a veracidade antes de seguir qualquer conselho. Aproveite para conhecer novos jogos, tirar dúvidas e perguntar como cada um funciona. Aprender com os outros é uma vantagem!",
  "📉 *Limite de perdas é essencial.*\nDefina um limite máximo de perda diária ou semanal e respeite-o para preservar sua banca.\n\n💡 Mude sua estratégia hoje: comece com um valor pequeno, vá aumentando aos poucos e analise semanalmente quanto foi lucro ou prejuízo. Jogador inteligente controla, registra e ajusta!",
  "📈 Foque no longo prazo, Evite se empolgar com ganhos rápidos e mantenha uma visão de crescimento gradual e constante.",
  "⏰ Pausas regulares, Faça pausas entre as sessões para evitar fadiga mental e perda de foco.",
  "📊 *Use ferramentas a seu favor.*\nAproveite planilhas, aplicativos ou softwares para organizar suas apostas, registrar resultados e analisar desempenho.\n\n📝 Sempre anote como foi seu desempenho do dia. Essa rotina ajuda você a evoluir com consciência e evitar repetir os mesmos erros.",
  "💸 Nunca aposte com dinheiro emprestado, Apostar com recursos que não são seus pode levar a sérios problemas financeiros e emocionais.",
  "🔔 Atenção às promoções, Fique atento às promoções e bônus das plataformas, mas leia os termos e condições para evitar surpresas.",
  "📱 Mantenha o foco, Evite distrações enquanto aposta para tomar decisões conscientes e rápidas.",
  "⚖️ Balanceie risco e retorno, Prefira apostas com risco controlado e retorno razoável ao invés de buscar ganhos altos com risco exagerado.",
  "🧘 Controle o estresse, Técnicas de respiração e meditação ajudam a manter a calma em momentos de pressão.",
  "📵 Evite apostas em horários inadequados, Não aposte quando estiver sob efeito de álcool, cansaço extremo ou estresse.",
  "🎯 Defina metas realistas, Metas impossíveis geram frustração. Seja honesto com seus objetivos.",
  "📦 Organize sua banca, Separe o dinheiro para apostas e não misture com outras finanças pessoais.",
  "🎯 Dica de consistência, Estabeleça um valor fixo para apostar diariamente e mantenha-se fiel a ele, independente dos resultados do dia.",
  "🔄 Reavalie frequentemente, Revise suas estratégias após cada sessão de apostas para ajustar o que funcionou e eliminar o que não deu certo.",
  "🛑 Sinal de alerta, Se perceber que está apostando para recuperar perdas, pare imediatamente. Isso é sinal de que a emoção está tomando conta.",
  "📚 Estude os jogos, Conheça as regras e particularidades de cada jogo onde aposta para tomar decisões mais informadas.",
  "👥 Use a comunidade, Busque dicas e análises em comunidades confiáveis, mas sempre cheque a veracidade antes de seguir qualquer conselho.",
  "📉 Limite de perdas, Defina um limite máximo de perda diária/semanal e respeite-o para preservar sua banca.",
  "📈 Foque no longo prazo, Evite se empolgar com ganhos rápidos e mantenha uma visão de crescimento gradual e constante.",
  "⏰ Pausas regulares, Faça pausas entre as sessões para evitar fadiga mental e perda de foco.",
  "📊 Use ferramentas, Aproveite planilhas, apps ou softwares para organizar suas apostas, registrar resultados e analisar desempenho.",
  "💸 Nunca aposte com dinheiro emprestado, Apostar com recursos que não são seus pode levar a sérios problemas financeiros e emocionais.",
  "🔔 Atenção às promoções, Fique atento às promoções e bônus das plataformas, mas leia os termos e condições para evitar surpresas.",
  "📱 Mantenha o foco, Evite distrações enquanto aposta para tomar decisões conscientes e rápidas.",
  "⚖️ Balanceie risco e retorno, Prefira apostas com risco controlado e retorno razoável ao invés de buscar ganhos altos com risco exagerado.",
  "🧘 Controle o estresse, Técnicas de respiração e meditação ajudam a manter a calma em momentos de pressão.",
  "📵 Evite apostas em horários inadequados, Não aposte quando estiver sob efeito de álcool, cansaço extremo ou estresse.",
   "🎯 Defina metas realistas, Metas impossíveis geram frustração. Seja honesto com seus objetivos.",
  "📦 Organize sua banca, Separe o dinheiro para apostas e não misture com outras finanças pessoais.",
  "🎁 *Promoções e meias ajudam, mas não fazem milagre.*\nUse como um impulso, não como estratégia principal.",
  "⚠️ *Atenção às promoções!*\nElas são um bônus, não garantia de ganho. Jogue com consciência, ecolha a plataforma pagante.",
  "💸 *Bônus não é lucro.*\nÉ só uma chance a mais. A estratégia sempre vem antes da promoção ou da meia banca.",
  "🎯 *Foco no jogo, não no brinde.*\nA promoção pode ajudar, mas quem garante o ganho é sua disciplina.",
  "📌 *Use a promoção como suporte.*\nNunca baseie sua aposta só porque ganhou bônus ou giro grátis.",
  "🧠 *Promoção não substitui estudo.*\nAposte com análise. O brinde é só um empurrão, não o motor da sua banca.",
  "💬 *Dica Importante:*\nPromoções servem para aumentar suas chances, mas não garantem resultados.",
  "📊 *Jogue como se não houvesse promoção.*\nSe vier bônus, ótimo. Mas sua estratégia deve ser independente disso.",
  "🎁 *Promoção é só cereja do bolo.*\nO que garante o lucro é controle, estratégia e escolha certa de jogos."
];

// Função que retorna uma dica aleatória já formatada com plataformas
function obterDicaAleatoria() {
  const indice = Math.floor(Math.random() * dicas.length);
  return dicas[indice];
}

module.exports = { obterDicaAleatoria };