const versiculos = [
  "Deus transforma lágrimas em testemunhos. O choro pode durar uma noite, mas a alegria vem pela manhã. Salmos capítulo 30, versículo 5.",
  "Quando você pensa em desistir, Deus já preparou a vitória. Posso todas as coisas naquele que me fortalece. Filipenses capítulo 4, versículo 13.",
  "Você não está sozinho. Deus cuida de você nos bastidores. Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós. Primeira carta de Pedro, capítulo 5, versículo 7.",
  "Mesmo no silêncio, Deus está trabalhando. Aquietai-vos e sabei que eu sou Deus. Salmos capítulo 46, versículo 10.",
  "A fé é o solo onde milagres crescem. Ora, a fé é o firme fundamento das coisas que se esperam e a prova das coisas que não se veem. Hebreus capítulo 11, versículo 1.",
  "Não temas o fogo da provação, pois Deus está contigo na fornalha. Quando passares pelo fogo, não te queimarás. Isaías capítulo 43, versículo 2.",
  "Você tem valor. Foi escolhido por Deus. Vós sois a geração eleita, o sacerdócio real, a nação santa. Primeira carta de Pedro, capítulo 2, versículo 9.",
  "Onde o mundo vê fim, Deus abre um novo começo. Eis que ponho diante de ti uma porta aberta, e ninguém a pode fechar. Apocalipse capítulo 3, versículo 8.",
  "Deus não falha. Sua promessa permanece mesmo nas tempestades. Fiel é o que prometeu. Hebreus capítulo 10, versículo 23.",
  "Há paz na presença dEle que o mundo não pode oferecer. Deixo-vos a paz, a minha paz vos dou. Evangelho de João, capítulo 14, versículo 27.",
  "Quem anda com Deus nunca está perdido. Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho. Salmos capítulo 119, versículo 105.",
  "O Senhor é o seu refúgio e fortaleza. Ainda que tudo desabe, Ele te sustenta. Salmos capítulo 46, versículo 1.",
  "A espera no Senhor nunca é em vão. Os que esperam no Senhor renovarão as suas forças. Isaías capítulo 40, versículo 31.",
  "Deus é especialista em impossíveis. Porque para Deus nada é impossível. Evangelho de Lucas, capítulo 1, versículo 37.",
  "O amor de Deus cobre multidão de erros. O amor cobre uma multidão de pecados. Primeira carta de Pedro, capítulo 4, versículo 8.",
  "A graça te basta. O poder de Deus se aperfeiçoa na fraqueza. Segunda carta aos Coríntios, capítulo 12, versículo 9.",
  "Confie no Senhor de todo o coração. Não te estribes no teu próprio entendimento. Provérbios capítulo 3, versículo 5.",
  "Deus ouve até o silêncio do seu coração. Antes mesmo que a palavra me chegue à língua, tu já a conheces. Salmos capítulo 139, versículo 4.",
  "Deus não chega atrasado. Tudo tem seu tempo determinado. Eclesiastes capítulo 3, versículo 1.",
  "Deus guarda seus filhos como a menina dos seus olhos. Salmos capítulo 17, versículo 8.",
  "No meio da guerra, Deus é tua paz. Deixo-vos a paz, a minha paz vos dou. Evangelho de João, capítulo 14, versículo 27.",
  "O Senhor não rejeita um coração quebrantado. Perto está o Senhor dos que têm o coração quebrantado. Salmos capítulo 34, versículo 18.",
  "A misericórdia do Senhor se renova a cada manhã. Lamentações capítulo 3, versículo 23.",
  "O Senhor é o meu pastor e nada me faltará. Salmos capítulo 23, versículo 1.",
  "Os que semeiam com lágrimas colherão com alegria. Salmos capítulo 126, versículo 5.",
  "Se Deus é por nós, quem será contra nós? Carta aos Romanos, capítulo 8, versículo 31.",
  "Maior é o que está em você do que o que está no mundo. Primeira carta de João, capítulo 4, versículo 4.",
  "A tua força vem do Senhor. O Senhor é a força da minha vida. Salmos capítulo 27, versículo 1.",
  "Entrega o teu caminho ao Senhor. Confia nele, e o mais ele fará. Salmos capítulo 37, versículo 5.",
  "Bendito é o homem que confia no Senhor. Jeremias capítulo 17, versículo 7.",
  "Tudo coopera para o bem dos que amam a Deus. Carta aos Romanos, capítulo 8, versículo 28.",
  "O Senhor pelejará por você. Êxodo capítulo 14, versículo 14.",
  "Não temas, porque eu sou contigo. Isaías capítulo 41, versículo 10.",
  "Buscai ao Senhor enquanto se pode achar. Isaías capítulo 55, versículo 6.",
  "O justo viverá da fé. Carta aos Hebreus, capítulo 10, versículo 38.",
  "Espera no Senhor. Anima-te, e ele fortalecerá o teu coração. Salmos capítulo 27, versículo 14.",
  "Tudo posso naquele que me fortalece. Filipenses capítulo 4, versículo 13.",
  "O Senhor firmará os teus passos. Salmos capítulo 40, versículo 2.",
  "Porque eu bem sei os pensamentos que tenho sobre vós, diz o Senhor. Jeremias capítulo 29, versículo 11.",
  "Aquele que começou a boa obra em você há de completá-la. Filipenses capítulo 1, versículo 6.",
  "Deus trabalha por aqueles que nele esperam. Isaías capítulo 64, versículo 4.",
  "Clama a mim e responder-te-ei. Jeremias capítulo 33, versículo 3.",
  "O Senhor é bom, um refúgio em tempos de angústia. Naum capítulo 1, versículo 7.",
  "Os anjos do Senhor acampam-se ao redor dos que o temem. Salmos capítulo 34, versículo 7.",
  "O Senhor é o meu rochedo, a minha fortaleza. Salmos capítulo 18, versículo 2.",
  "Melhor é confiar no Senhor do que confiar no homem. Salmos capítulo 118, versículo 8.",
  "Deleita-te também no Senhor, e ele concederá os desejos do teu coração. Salmos capítulo 37, versículo 4.",
  "Não andeis ansiosos por coisa alguma. Filipenses capítulo 4, versículo 6.",
  "O Senhor está perto dos que o invocam em verdade. Salmos capítulo 145, versículo 18.",
  "O Senhor é a minha luz e a minha salvação. Salmos capítulo 27, versículo 1.",
  "Aquietai-vos e sabei que eu sou Deus. Salmos capítulo 46, versículo 10.",
  "A bênção do Senhor enriquece. Provérbios capítulo 10, versículo 22.",
  "Deus é a nossa torre segura. Provérbios capítulo 18, versículo 10.",
  "A alegria do Senhor é a nossa força. Neemias capítulo 8, versículo 10.",
  "Bem-aventurados os que confiam no Senhor. Salmos capítulo 84, versículo 12.",
  "Confia no Senhor eternamente, pois o Senhor Deus é uma rocha eterna. Isaías capítulo 26, versículo 4.",
  "Guarda o teu coração, porque dele procedem as fontes da vida. Provérbios capítulo 4, versículo 23.",
  "O Senhor dirige os passos do homem. Salmos capítulo 37, versículo 23.",
  "O temor do Senhor é o princípio da sabedoria. Provérbios capítulo 9, versículo 10.",
  "Louvarei ao Senhor em todo o tempo. Salmos capítulo 34, versículo 1.",
  "Buscai primeiro o Reino de Deus. Evangelho de Mateus, capítulo 6, versículo 33.",
  "Bem-aventurados os limpos de coração, porque verão a Deus. Evangelho de Mateus, capítulo 5, versículo 8.",
  "O Senhor renova as suas misericórdias a cada manhã. Lamentações capítulo 3, versículo 22.",
  "Sede fortes e corajosos. Deuteronômio capítulo 31, versículo 6.",
  "A palavra do Senhor é perfeita e refrigera a alma. Salmos capítulo 19, versículo 7.",
  "O Senhor abrirá os céus para abençoar você. Deuteronômio capítulo 28, versículo 12.",
  "Não se turbe o vosso coração. Evangelho de João, capítulo 14, versículo 1.",
  "Bem-aventurados os que ouvem a palavra de Deus e a guardam. Evangelho de Lucas, capítulo 11, versículo 28.",
  "Quem habita no esconderijo do Altíssimo, à sombra do Onipotente descansará. Salmos capítulo 91, versículo 1.",
  "O Senhor é contigo, homem valente. Juízes capítulo 6, versículo 12.",
  "O Senhor cura os de coração quebrantado. Salmos capítulo 147, versículo 3.",
  "Com Deus faremos proezas. Salmos capítulo 60, versículo 12.",
  "Não te deixes vencer do mal, mas vence o mal com o bem. Romanos capítulo 12, versículo 21.",
  "Bem-aventurados os pacificadores, porque serão chamados filhos de Deus. Mateus capítulo 5, versículo 9.",
  "Aquele que habita em você é maior. Primeira carta de João, capítulo 4, versículo 4.",
  "Deus é fiel. Primeira carta aos Coríntios, capítulo 1, versículo 9.",
  "Deus é amor. Primeira carta de João, capítulo 4, versículo 8.",
  "Tudo que pedirdes em oração, crendo, recebereis. Mateus capítulo 21, versículo 22.",
  "Se creres, verás a glória de Deus. João capítulo 11, versículo 40.",
  "Bem-aventurados os que têm fome e sede de justiça. Mateus capítulo 5, versículo 6.",
  "Se andarmos na luz, como Ele na luz está, temos comunhão uns com os outros. Primeira carta de João, capítulo 1, versículo 7.",
  "Confiai no Senhor perpetuamente. Isaías capítulo 26, versículo 4.",
  "O Senhor é escudo para os que nele confiam. Provérbios capítulo 30, versículo 5.",
  "É melhor obedecer do que sacrificar. Primeiro livro de Samuel, capítulo 15, versículo 22.",
  "Nisto conhecerão que sois meus discípulos: se vos amardes uns aos outros. João capítulo 13, versículo 35.",
  "Perseverai na oração. Romanos capítulo 12, versículo 12.",
  "Vinde a mim, todos os que estais cansados e sobrecarregados. Mateus capítulo 11, versículo 28.",
  "Não vos conformeis com este mundo. Romanos capítulo 12, versículo 2.",
  "Sede santos, porque eu sou santo. Primeira carta de Pedro, capítulo 1, versículo 16.",
  "Com alegria tirareis águas das fontes da salvação. Isaías capítulo 12, versículo 3.",
  "Pela graça sois salvos, por meio da fé. Efésios capítulo 2, versículo 8.",
  "Cantai ao Senhor um cântico novo. Salmos capítulo 96, versículo 1.",
  "Andareis em meus caminhos e guardareis os meus estatutos. Ezequiel capítulo 36, versículo 27.",
  "Seja forte e corajoso. Josué capítulo 1, versículo 9."
];

module.exports = versiculos;